/**
 * `vura build` — Build the project for deployment.
 *
 * 1. Scan routes → build manifest
 * 2. Generate server entry (for hot server)
 * 3. Generate function entries (for serverless)
 * 4. Generate task entries (for task routes)
 * 5. Bundle server-mode pages with esbuild
 * 6. Render static pages (mode: 'static')
 * 7. Run adapter.buildEnd() if configured
 * 8. Write manifest.json
 * 9. Emit hot deploy templates (Dockerfile, fly.toml, package.json) when hot routes present
 */

import { buildManifest, build, renderStaticPages, generateClientPageEntry, vuraBrowserResolvePlugin, vuraActionsStubPlugin } from '@celsian/vura-core';
import { createRequire } from 'node:module';
import { existsSync, readFileSync } from 'node:fs';
import { join as pathJoin, resolve as pathResolve, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import { loadConfig } from '../config-loader.js';

/**
 * Remove hashed page bundles that this build did not emit.
 *
 * Bundle filenames carry a content hash, so every edit to a client or hybrid
 * page produces a new name and orphans the old one. Nothing removed those, so
 * `dist/static/_then/pages` grew with every incremental build and the dead
 * copies shipped to whatever the project deployed to.
 *
 * Recursive, because pages nest (`loaders/island.js`). Empty directories left
 * behind by a deleted page are removed too. `fs` is injected so this can be
 * tested without touching a disk.
 */
export async function pruneStaleBundles(
  dir: string,
  keep: Set<string>,
  fs: {
    readdir: (p: string, o: { withFileTypes: true }) => Promise<Array<{ name: string; isDirectory: () => boolean }>>;
    rm: (p: string, o?: { recursive?: boolean; force?: boolean }) => Promise<void>;
  },
): Promise<number> {
  let removed = 0;
  let entries: Array<{ name: string; isDirectory: () => boolean }>;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return 0; // nothing was written here
  }

  for (const entry of entries) {
    const full = pathJoin(dir, entry.name);
    if (entry.isDirectory()) {
      removed += await pruneStaleBundles(full, keep, fs);
      // The page that lived here is gone; do not leave the empty shell.
      try {
        const rest = await fs.readdir(full, { withFileTypes: true });
        if (rest.length === 0) await fs.rm(full, { recursive: true, force: true });
      } catch {
        /* raced or unreadable: leaving it is harmless */
      }
      continue;
    }
    if (keep.has(full)) continue;
    await fs.rm(full, { force: true });
    removed++;
  }
  return removed;
}

// ---------------------------------------------------------------------------
// Deploy template strings — inlined so they survive tsc compilation (tsc does
// not copy non-TS assets).  Emitted by emitHotDeployTemplates() when hot
// routes are detected.
// ---------------------------------------------------------------------------

// NOTE: Both files are regenerated by `vura build` — hand-edits will be overwritten.
//
// Dockerfile context is the dist/ directory itself.
//   docker build -f dist/Dockerfile dist
//
// fly.toml deploy flow (flyctl resolves fly.toml from the given directory and
// uses that directory as the Docker build context):
//   fly deploy ./dist

const DOCKERFILE_HOT = `\
# Generated by vura build — hand-edits will be overwritten on next build.
# Build context must be the dist/ directory:
#   docker build -f dist/Dockerfile dist
FROM node:22-slim
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev --no-audit --no-fund
COPY . ./
ENV NODE_ENV=production PORT=3000
EXPOSE 3000
CMD ["node", "server/entry.js"]
`;

const FLY_TOML_TMPL = `\
# Generated by vura build — hand-edits will be overwritten on next build.
# Deploy with: fly deploy ./dist
# (flyctl picks up this fly.toml from ./dist and uses ./dist as build context)
app = "{{APP_NAME}}"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  # auto_stop_machines is off because hot routes hold in-memory websocket state
  auto_stop_machines = "off"
  min_machines_running = 1
`;

const nativeImport = (specifier: string): Promise<any> => import(/* @vite-ignore */ specifier);

/**
 * Write dist/package.json.
 *
 * `npm install --omit=dev` inside the Docker build resolves against this file,
 * so it has to list every bare specifier the emitted bundles still import at
 * runtime. Two do:
 *
 *   - `what-framework`, because API and page route modules are bundled with it
 *     kept external (see bundleRouteModule's `keepWhatFwExternal`). Without the
 *     dependency the container starts and dies on the first request to any API
 *     route with `ERR_MODULE_NOT_FOUND: what-framework/server`. It was only ever
 *     absent from this file, never from the imports.
 *   - `ws`, when the project has WebSocket routes.
 *
 * It is pinned to the version the project actually resolved, so the container
 * runs the What the app was built and tested against rather than whatever
 * `latest` is on deploy day.
 *
 * This runs for EVERY build. It used to run only for projects with hot routes,
 * which is unrelated to whether the bundles import anything.
 */
async function emitDeployPackageJson(
  distDir: string,
  projectRoot: string,
  hasWsRoutes: boolean,
): Promise<void> {
  const { writeFile, readFile, mkdir } = await import('node:fs/promises');
  const { existsSync } = await import('node:fs');
  const { join } = await import('node:path');

  await mkdir(distDir, { recursive: true });

  const pkgPath = join(distDir, 'package.json');
  let existing: Record<string, unknown> = {};
  if (existsSync(pkgPath)) {
    try {
      existing = JSON.parse(await readFile(pkgPath, 'utf8'));
    } catch {
      console.warn('  Warning: dist/package.json is malformed JSON — regenerating from scratch.');
    }
  }

  const deps: Record<string, string> = { ...((existing.dependencies as Record<string, string>) ?? {}) };

  const whatVersion = resolveWhatFrameworkVersion(projectRoot);
  if (whatVersion) {
    deps['what-framework'] = whatVersion;
  } else {
    console.warn(
      '  Warning: could not resolve what-framework in this project, so dist/package.json ' +
      'does not declare it. A container build will fail to resolve `what-framework/server` ' +
      'from the emitted API route bundles.',
    );
  }

  if (hasWsRoutes) deps.ws = '8.18.0';

  const merged: Record<string, unknown> = { ...existing, type: 'module' };
  if (Object.keys(deps).length > 0) merged.dependencies = deps;

  await writeFile(pkgPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
}

/** The exact what-framework version installed in the project, or null. */
/**
 * Import specifiers for a page's layout chain, relative to the page's own
 * directory (the resolveDir the generated browser entry is bundled with).
 */
function layoutSpecifiersFor(
  page: { filePath: string; layouts?: string[] },
  projectRoot: string,
): string[] {
  const pageDir = pathResolve(projectRoot, page.filePath, '..');
  return (page.layouts ?? []).map((layoutPath) => {
    const rel = relative(pageDir, pathResolve(projectRoot, layoutPath)).replace(/\\/g, '/');
    return rel.startsWith('.') ? rel : `./${rel}`;
  });
}

function resolveWhatFrameworkVersion(projectRoot: string): string | null {
  // Read the installed package.json off disk instead of resolving the
  // specifier. `require('what-framework/package.json')` looks like the obvious
  // way to do this and cannot work: what-framework's `exports` map lists `.`,
  // `./server`, `./router` and friends, and Node refuses any subpath an
  // exports map does not name — including './package.json'. Every real install
  // therefore threw ERR_PACKAGE_PATH_NOT_EXPORTED, the version came back null,
  // and dist/package.json shipped without the dependency the container needs.
  let dir = projectRoot;
  for (let depth = 0; depth < 10; depth++) {
    const candidate = pathJoin(dir, 'node_modules', 'what-framework', 'package.json');
    if (existsSync(candidate)) {
      try {
        const manifest = JSON.parse(readFileSync(candidate, 'utf8')) as { version?: string };
        if (typeof manifest.version === 'string') return manifest.version;
      } catch {
        return null;
      }
      return null;
    }
    const parent = pathResolve(dir, '..');
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

/**
 * Emit Dockerfile and fly.toml into dist/ when the project has hot routes.
 */
async function emitHotDeployTemplates(
  distDir: string,
  appName: string,
): Promise<void> {
  const { writeFile, mkdir } = await import('node:fs/promises');
  const { join } = await import('node:path');

  await mkdir(distDir, { recursive: true });

  // Dockerfile
  await writeFile(join(distDir, 'Dockerfile'), DOCKERFILE_HOT, 'utf8');

  // fly.toml — replace {{APP_NAME}} placeholder
  const flyToml = FLY_TOML_TMPL.replace('{{APP_NAME}}', appName);
  await writeFile(join(distDir, 'fly.toml'), flyToml, 'utf8');
}

export async function buildCommand(_args: string[]): Promise<void> {
  const startTime = Date.now();
  const projectRoot = process.cwd();

  console.log('\n  vura build\n');

  // 1. Load config
  const config = await loadConfig(projectRoot);
  const root = config.root ?? projectRoot;
  console.log(`  Root: ${root}`);

  // 2. Scan routes
  console.log('  Scanning routes...');
  const manifest = await buildManifest(root);

  const serverlessCount = manifest.api.filter(r => r.kind === 'serverless').length;
  const hotCount = manifest.api.filter(r => r.kind === 'hot').length;
  const taskCount = manifest.api.filter(r => r.kind === 'task').length;

  console.log(`  Found ${manifest.api.length} API routes (${serverlessCount} serverless, ${hotCount} hot, ${taskCount} task)`);
  console.log(`  Found ${manifest.pages.length} pages`);

  // Shared esbuild helpers
  const { build: esbuild } = await import('esbuild');
  const { join, resolve } = await import('node:path');
  const { mkdir, readFile, rename, rm, readdir } = await import('node:fs/promises');
  const { existsSync } = await import('node:fs');
  const { createHash } = await import('node:crypto');

  const cliRequire = createRequire(import.meta.url);
  const projectRequire = createRequire(join(root, 'package.json'));

  // Determine JSX import source from the user's project, not from the CLI's own
  // dependency graph. Use ESM resolution because What Framework exposes
  // jsx-runtime under import conditions, not CommonJS require conditions.
  let jsxImportSource = '@celsian/vura-core';
  try {
    await import('what-framework' + '/jsx-runtime');
    jsxImportSource = 'what-framework';
    console.log('  Using What Framework JSX runtime');
  } catch {
    console.log('  Using built-in JSX runtime');
  }

  // Plugin to help esbuild resolve ESM-only package exports.
  // Searches from the project root first (the user's installed copy), then
  // from the CLI's own location (monorepo/test environments).
  const { fileURLToPath } = await import('node:url');
  const { dirname: pathDirname } = await import('node:path');
  const cliDir = pathDirname(fileURLToPath(import.meta.url));
  function findNodeModules(pkg: string): string {
    for (const base of [root, cliDir]) {
      let dir = base;
      for (let depth = 0; depth < 10; depth++) {
        const candidate = join(dir, 'node_modules', pkg);
        if (existsSync(candidate)) return candidate;
        const parent = resolve(dir, '..');
        if (parent === dir) break;
        dir = parent;
      }
    }
    return join(root, 'node_modules', pkg);
  }

  /**
   * Resolve the bare specifiers esbuild cannot.
   *
   * `inlineWhatFramework` decides what happens to `what-framework` and
   * `what-core`. A browser bundle needs them inlined — there is no module
   * resolution in a browser, and their exports maps are import-condition-only,
   * so `require.resolve` cannot find them. A **server** bundle must keep them
   * external, and this is the switch that says which.
   *
   * It exists because an `onResolve` that returns a path *beats* esbuild's
   * `external` list. Setting both, as the build-time page loader did, silently
   * loses: the page module inlined its own copy of what-core while
   * `renderToString` ran from the installed one, the two disagreed about which
   * component was rendering, and `useSignal()` threw "can only be called
   * inside a component function" in every `static` and `hybrid` page. Loaders
   * escaped it only because `@celsian/vura-core` is not intercepted here.
   */
  const makeEsmResolvePlugin = ({ inlineWhatFramework }: { inlineWhatFramework: boolean }) => ({
    name: 'esm-resolve',
    setup(build: any) {
      build.onResolve({ filter: /^@celsian\/vura-core\/(jsx-runtime|jsx-dev-runtime)$/ }, (args: any) => {
        try {
          return { path: projectRequire.resolve(args.path) };
        } catch {
          return { path: cliRequire.resolve(args.path) };
        }
      });

      if (!inlineWhatFramework) return;

      // Bare what-framework/what-core imports (the generated client entry
      // imports { h, mount, hydrate } from 'what-framework'). The exports map
      // is import-condition-only, so require.resolve can't find it — resolve
      // to the package's ESM source entry directly.
      build.onResolve({ filter: /^what-(framework|core)$/ }, (args: any) => {
        const candidate = join(findNodeModules(args.path), 'src', 'index.js');
        if (existsSync(candidate)) return { path: candidate };
        return null; // fall through to esbuild's default resolution
      });

      build.onResolve({ filter: /^what-(framework|core)\// }, (args: any) => {
        const parts = args.path.split('/');
        const pkg = parts[0];
        const subpath = parts.slice(1).join('/');
        const pkgDir = findNodeModules(pkg);
        const candidates = [
          join(pkgDir, 'src', subpath + '.js'),
          join(pkgDir, 'src', subpath, 'index.js'),
        ];
        for (const candidate of candidates) {
          if (existsSync(candidate)) {
            return { path: candidate };
          }
        }
        return null;
      });
    },
  });

  /** Externals every server-side bundle shares: one framework copy per process. */

  /** Browser bundles: what-framework is inlined, because a browser has no resolver. */
  const browserEsmResolvePlugin = makeEsmResolvePlugin({ inlineWhatFramework: true });
  /** Server bundles: what-framework stays external, so the process holds one copy. */
  const serverEsmResolvePlugin = makeEsmResolvePlugin({ inlineWhatFramework: false });

  // Steps 3a and 3b used to live here: the CLI bundled every server-mode page
  // and every layout into `dist/server/pages/`, and then core's `build()` ran
  // `bundleServerPageModules()` over the same inputs and overwrote every one of
  // those files. The output was byte-identical, so the only thing the CLI's
  // copy produced was a second esbuild pass per page and per layout on every
  // build, plus a second copy of the resolve configuration to keep in sync with
  // core's. The `useSignal` bug shipped through exactly that kind of duplicate:
  // one copy was fixed and the other was not.
  //
  // Page and layout bundling now happens once, in core. `serverEsmResolvePlugin`
  // below is still used for the standalone entry.

  // 3c. Bundle browser entries for client and hybrid pages.
  // Each bundle is a generated wrapper (generateClientPageEntry) that imports
  // the page module and calls mount() (client) / hydrate() (hybrid) — bundling
  // the raw page module alone leaves the shell at "Loading..." forever because
  // nothing ever boots the component.
  const browserPages = manifest.pages.filter(p => p.mode === 'client' || p.mode === 'hybrid');
  const clientScripts: Record<string, string> = {};
  if (browserPages.length > 0) {
    console.log(`  Bundling ${browserPages.length} browser page entries...`);
    const clientPagesDir = join(root, 'dist', 'static', '_then', 'pages');
    await mkdir(clientPagesDir, { recursive: true });
    // Every bundle this build writes. Anything else under the directory is a
    // bundle from an earlier build whose content hash has since changed, and
    // nothing references it any more.
    const emittedBundles = new Set<string>();

    const { dirname, basename } = await import('node:path');
    for (const page of browserPages) {
      const absPath = resolve(root, page.filePath);
      const outFile = page.filePath.replace(/^src\/pages\//, '').replace(/\.(tsx|jsx|ts|js)$/, '.js');
      const outPath = join(clientPagesDir, outFile);
      await mkdir(join(outPath, '..'), { recursive: true });

      await esbuild({
        stdin: {
          contents: generateClientPageEntry(
            `./${basename(absPath)}`,
            page.mode as 'client' | 'hybrid',
            // The server rendered this page inside its layouts, so the browser
            // has to hydrate the same tree. Specifiers are relative to the
            // page's own directory, which is the entry's resolveDir.
            { layoutImportSpecifiers: layoutSpecifiersFor(page, root) },
          ),
          resolveDir: dirname(absPath),
          sourcefile: '__vura-client-entry__.js',
          loader: 'js',
        },
        bundle: true,
        format: 'esm',
        target: 'es2022',
        platform: 'browser',
        outfile: outPath,
        jsx: 'automatic',
        jsxImportSource,
        // Browser-resolve first: a page that imports `@celsian/vura-core` for
        // useLoaderData must get the pure client module here, not the package
        // root, which reaches node:fs and cannot be bundled for a browser.
        //
        // The actions stub plugin is the security boundary for `src/actions/`:
        // it answers onResolve, so esbuild never opens an action file for this
        // bundle and nothing inside one can reach the browser.
        plugins: [
          vuraBrowserResolvePlugin(),
          vuraActionsStubPlugin({ projectRoot: root }),
          browserEsmResolvePlugin,
        ],
        external: [],
      });

      const bundleHash = createHash('sha256')
        .update(await readFile(outPath))
        .digest('hex')
        .slice(0, 12);
      const hashedOutFile = outFile.replace(/\.js$/, `.${bundleHash}.js`);
      await rename(outPath, join(clientPagesDir, hashedOutFile));
      emittedBundles.add(join(clientPagesDir, hashedOutFile));

      const scriptPath = `/_then/pages/${hashedOutFile.replace(/\\/g, '/')}`;
      clientScripts[page.filePath] = scriptPath;
      console.log(`    ◇ ${page.urlPattern} → dist/static${scriptPath}`);
    }

    // Drop bundles left behind by earlier builds. The filename carries a
    // content hash, so editing a page emits a new name and orphans the old
    // one, which nothing then removes: `dist/` grew with every incremental
    // build and shipped the dead copies to whatever you deployed to.
    //
    // Pruning *after* the writes rather than wiping the directory first is
    // deliberate. A build that fails partway leaves the previous bundles
    // intact instead of leaving nothing to serve.
    const pruned = await pruneStaleBundles(clientPagesDir, emittedBundles, { readdir, rm });
    if (pruned > 0) {
      console.log(`    ✓ removed ${pruned} stale bundle${pruned === 1 ? '' : 's'} from earlier builds`);
    }
  }

  // 4. Build API routes + task entries
  console.log('  Building...');
  const result = await build(manifest, config, root);

  console.log(`  Server entry: ${result.serverEntry}`);
  console.log(`  Functions: ${result.functions.length} serverless bundles`);
  if (result.taskEntries.length > 0) {
    console.log(`  Tasks: ${result.taskEntries.length} task entries`);
  }

  // 5. Render build-time pages (static, client shells, and hybrid prerendered HTML)
  const staticPages = manifest.pages.filter(p => p.mode !== 'server');
  if (staticPages.length > 0) {
    console.log(`  Rendering ${staticPages.length} build-time pages...`);

    const tmpDir = join(root, 'dist', '.page-tmp');
    await mkdir(tmpDir, { recursive: true });

    // A build-time page is imported into THIS process and rendered by core's
    // own `renderToString`. Two rules follow, and breaking either one produces
    // a failure that looks like a framework bug rather than a bundling one:
    //
    //  1. `what-framework` and `@celsian/vura-core` stay external. Inlining
    //     them gives the page a second copy of the framework, with its own
    //     "currently rendering component" and its own context registry — so
    //     every hook the page calls, `useLoaderData` included, reads a
    //     registry that the renderer never wrote to and reports being called
    //     outside a render.
    //  2. The bundle is written to a real file rather than imported as a
    //     `data:` URL. A data: module has no parent path, so it cannot resolve
    //     the bare specifiers rule 1 just created, and anything it does inline
    //     that calls `fileURLToPath(import.meta.url)` at module scope throws
    //     "The URL must be of scheme file".
    const sharedRuntimeExternals = [
      'what-framework',
      'what-framework/*',
      '@celsian/vura-core',
      '@celsian/vura-core/*',
    ];
    let pageModuleSeq = 0;
    const loadModule = async (filePath: string) => {
      const absPath = resolve(root, filePath);
      const tmpFile = join(tmpDir, `page-${pageModuleSeq++}.mjs`);
      await esbuild({
        entryPoints: [absPath],
        bundle: true,
        format: 'esm',
        target: 'es2022',
        platform: 'node',
        outfile: tmpFile,
        jsx: 'automatic',
        jsxImportSource,
        plugins: [serverEsmResolvePlugin],
        external: sharedRuntimeExternals,
      });
      return nativeImport(pathToFileURL(tmpFile).href);
    };

    const outDir = join(root, 'dist');
    const rendered = await renderStaticPages(staticPages, loadModule, outDir, { clientScripts });

    for (const page of rendered) {
      console.log(`    ◆ ${page.urlPattern} → ${page.outputPath.replace(root + '/', '')}`);
    }

    // Clean up temp files
    const { rm } = await import('node:fs/promises');
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }

  // 6. Copy public assets to dist/public/ for production static serving.
  // Prefer the framework-standard root public/ directory, but support the
  // historical starter/runbook layout src/public/ when root public/ is absent.
  const publicDir = join(root, 'public');
  const legacySrcPublicDir = join(root, 'src', 'public');
  const publicSourceDir = existsSync(publicDir)
    ? publicDir
    : existsSync(legacySrcPublicDir)
      ? legacySrcPublicDir
      : null;
  if (publicSourceDir) {
    const { cp } = await import('node:fs/promises');
    const distPublicDir = join(root, 'dist', 'public');
    await cp(publicSourceDir, distPublicDir, { recursive: true });
    const label = publicSourceDir === publicDir ? 'public/' : 'src/public/';
    console.log(`  Copied ${label} → dist/public/`);
  }

  if (config.adapter) {
    console.log(`  Adapter: ${config.adapter.name}`);
  }

  // 9. Emit hot deploy templates when the project has hot routes
  const hotRoutes = manifest.api.filter(r => r.kind === 'hot');
  const hasWsRoutes = hotRoutes.some(r => r.hasWebsocket === true);
  const distDir = join(root, 'dist');

  // Always: the emitted bundles import `what-framework` at runtime whether or
  // not the project has hot routes.
  await emitDeployPackageJson(distDir, root, hasWsRoutes);

  if (hotRoutes.length > 0) {
    const { basename } = await import('node:path');
    const rawName = basename(root);
    // sanitize to lowercase [a-z0-9-], truncate to Fly's ~30-char DNS label limit,
    // then strip any trailing dashes introduced by truncation
    const appName = rawName.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 30).replace(/-+$/, '') || 'vura-app';
    await emitHotDeployTemplates(distDir, appName);
    console.log(`  Emitted dist/Dockerfile, dist/fly.toml, dist/package.json (app: ${appName}${hasWsRoutes ? ', ws: true' : ''})`);
  }

  const elapsed = Date.now() - startTime;
  console.log(`\n  Build complete in ${elapsed}ms\n`);

  // Print route table
  console.log('  Routes:');
  for (const route of manifest.api) {
    const methods = route.methods.join(', ');
    const icon = route.kind === 'serverless' ? 'λ' : route.kind === 'hot' ? '●' : '⏳';
    console.log(`    ${icon} ${methods.padEnd(18)} ${route.urlPattern.padEnd(30)} ${route.kind}`);
  }

  for (const page of manifest.pages) {
    const icon = page.mode === 'static' ? '◆' : page.mode === 'server' ? '◈' : page.mode === 'client' ? '◇' : '⬡';
    console.log(`    ${icon} ${'PAGE'.padEnd(18)} ${page.urlPattern.padEnd(30)} ${page.mode}`);
  }

  console.log();
}
