/**
 * `vura build` — Build the project for deployment.
 *
 * 1. Scan routes → build manifest
 * 2. Generate server entry (for hot server)
 * 3. Generate function entries (for serverless)
 * 4. Generate task entries (for task routes)
 * 5. Bundle server-mode pages with esbuild
 * 6. Render static pages (mode: 'static')
 * 7. Run adapter.buildEnd() if configured
 * 8. Write manifest.json
 * 9. Emit hot deploy templates (Dockerfile, fly.toml, package.json) when hot routes present
 */

import { buildManifest, build, renderStaticPages } from '@celsian/vura-core';
import { createRequire } from 'node:module';
import { Buffer } from 'node:buffer';
import { loadConfig } from '../config-loader.js';

// ---------------------------------------------------------------------------
// Deploy template strings — inlined so they survive tsc compilation (tsc does
// not copy non-TS assets).  Emitted by emitHotDeployTemplates() when hot
// routes are detected.
// ---------------------------------------------------------------------------

// NOTE: Both files are regenerated by `vura build` — hand-edits will be overwritten.
//
// Dockerfile context is the dist/ directory itself.
//   docker build -f dist/Dockerfile dist
//
// fly.toml deploy flow (flyctl resolves fly.toml from the given directory and
// uses that directory as the Docker build context):
//   fly deploy ./dist

const DOCKERFILE_HOT = `\
# Generated by vura build — hand-edits will be overwritten on next build.
# Build context must be the dist/ directory:
#   docker build -f dist/Dockerfile dist
FROM node:22-slim
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev --no-audit --no-fund
COPY . ./
ENV NODE_ENV=production PORT=3000
EXPOSE 3000
CMD ["node", "server/entry.js"]
`;

const FLY_TOML_TMPL = `\
# Generated by vura build — hand-edits will be overwritten on next build.
# Deploy with: fly deploy ./dist
# (flyctl picks up this fly.toml from ./dist and uses ./dist as build context)
app = "{{APP_NAME}}"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  # auto_stop_machines is off because hot routes hold in-memory websocket state
  auto_stop_machines = "off"
  min_machines_running = 1
`;

const nativeImport = (specifier: string): Promise<any> => import(/* @vite-ignore */ specifier);
const moduleSourceToDataUrl = (source: string): string => `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;

/**
 * Emit Dockerfile and fly.toml into dist/ when the project has hot routes.
 * Also writes/merges dist/package.json so that `npm install --omit=dev` in the
 * Docker build pulls the right runtime deps (ws when WS routes are present).
 */
async function emitHotDeployTemplates(
  distDir: string,
  appName: string,
  hasWsRoutes: boolean,
): Promise<void> {
  const { writeFile, readFile, mkdir } = await import('node:fs/promises');
  const { existsSync } = await import('node:fs');
  const { join } = await import('node:path');

  await mkdir(distDir, { recursive: true });

  // Dockerfile
  await writeFile(join(distDir, 'Dockerfile'), DOCKERFILE_HOT, 'utf8');

  // fly.toml — replace {{APP_NAME}} placeholder
  const flyToml = FLY_TOML_TMPL.replace('{{APP_NAME}}', appName);
  await writeFile(join(distDir, 'fly.toml'), flyToml, 'utf8');

  // dist/package.json — create or merge
  const pkgPath = join(distDir, 'package.json');
  let existing: Record<string, unknown> = {};
  if (existsSync(pkgPath)) {
    try {
      existing = JSON.parse(await readFile(pkgPath, 'utf8'));
    } catch {
      console.warn('  Warning: dist/package.json is malformed JSON — regenerating from scratch.');
    }
  }

  const merged: Record<string, unknown> = { ...existing, type: 'module' };
  if (hasWsRoutes) {
    const existingDeps = (existing.dependencies as Record<string, string> | undefined) ?? {};
    merged.dependencies = { ...existingDeps, ws: '8.18.0' };
  }

  await writeFile(pkgPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
}

export async function buildCommand(_args: string[]): Promise<void> {
  const startTime = Date.now();
  const projectRoot = process.cwd();

  console.log('\n  vura build\n');

  // 1. Load config
  const config = await loadConfig(projectRoot);
  const root = config.root ?? projectRoot;
  console.log(`  Root: ${root}`);

  // 2. Scan routes
  console.log('  Scanning routes...');
  const manifest = await buildManifest(root);

  const serverlessCount = manifest.api.filter(r => r.kind === 'serverless').length;
  const hotCount = manifest.api.filter(r => r.kind === 'hot').length;
  const taskCount = manifest.api.filter(r => r.kind === 'task').length;

  console.log(`  Found ${manifest.api.length} API routes (${serverlessCount} serverless, ${hotCount} hot, ${taskCount} task)`);
  console.log(`  Found ${manifest.pages.length} pages`);

  // Shared esbuild helpers
  const { build: esbuild } = await import('esbuild');
  const { join, resolve } = await import('node:path');
  const { mkdir } = await import('node:fs/promises');
  const { existsSync } = await import('node:fs');

  const cliRequire = createRequire(import.meta.url);
  const projectRequire = createRequire(join(root, 'package.json'));

  // Determine JSX import source from the user's project, not from the CLI's own
  // dependency graph. Use ESM resolution because What Framework exposes
  // jsx-runtime under import conditions, not CommonJS require conditions.
  let jsxImportSource = '@celsian/vura-core';
  try {
    await import('what-framework' + '/jsx-runtime');
    jsxImportSource = 'what-framework';
    console.log('  Using What Framework JSX runtime');
  } catch {
    console.log('  Using built-in JSX runtime');
  }

  // Plugin to help esbuild resolve ESM-only package exports
  function findNodeModules(pkg: string): string {
    let pkgDir = join(root, 'node_modules', pkg);
    if (existsSync(pkgDir)) return pkgDir;
    let dir = root;
    for (let depth = 0; depth < 5; depth++) {
      const parent = resolve(dir, '..');
      if (parent === dir) break;
      dir = parent;
      const candidate = join(dir, 'node_modules', pkg);
      if (existsSync(candidate)) return candidate;
    }
    return pkgDir;
  }

  const esmResolvePlugin = {
    name: 'esm-resolve',
    setup(build: any) {
      build.onResolve({ filter: /^@celsian\/vura-core\/(jsx-runtime|jsx-dev-runtime)$/ }, (args: any) => {
        try {
          return { path: projectRequire.resolve(args.path) };
        } catch {
          return { path: cliRequire.resolve(args.path) };
        }
      });

      build.onResolve({ filter: /^what-(framework|core)\// }, (args: any) => {
        const parts = args.path.split('/');
        const pkg = parts[0];
        const subpath = parts.slice(1).join('/');
        const pkgDir = findNodeModules(pkg);
        const candidates = [
          join(pkgDir, 'src', subpath + '.js'),
          join(pkgDir, 'src', subpath, 'index.js'),
        ];
        for (const candidate of candidates) {
          if (existsSync(candidate)) {
            return { path: candidate };
          }
        }
        return null;
      });
    },
  };

  // 3. Bundle server-mode pages
  const serverPages = manifest.pages.filter(p => p.mode === 'server' || p.mode === 'hybrid');
  if (serverPages.length > 0) {
    console.log(`  Bundling ${serverPages.length} server-mode pages...`);
    const serverPagesDir = join(root, 'dist', 'server', 'pages');
    await mkdir(serverPagesDir, { recursive: true });

    for (const page of serverPages) {
      const absPath = resolve(root, page.filePath);
      const outFile = page.filePath.replace(/^src\/pages\//, '').replace(/\.tsx?$/, '.js');
      const outPath = join(serverPagesDir, outFile);
      await mkdir(join(outPath, '..'), { recursive: true });

      await esbuild({
        entryPoints: [absPath],
        bundle: true,
        format: 'esm',
        target: 'es2022',
        platform: 'node',
        outfile: outPath,
        jsx: 'automatic',
        jsxImportSource,
        plugins: [esmResolvePlugin],
        external: [],
      });

      console.log(`    ◈ ${page.urlPattern} → dist/server/pages/${outFile}`);
    }
  }

  // 3b. Bundle layout files used by server-mode pages
  if (manifest.layouts.length > 0 && serverPages.length > 0) {
    // Only compile layouts that are actually referenced by server-mode pages
    const usedLayoutPaths = new Set<string>();
    for (const page of serverPages) {
      if (page.layouts) {
        for (const lp of page.layouts) usedLayoutPaths.add(lp);
      }
    }

    const layoutsToCompile = manifest.layouts.filter(l => usedLayoutPaths.has(l.filePath));
    if (layoutsToCompile.length > 0) {
      console.log(`  Bundling ${layoutsToCompile.length} layout files...`);
      const serverPagesDir = join(root, 'dist', 'server', 'pages');
      await mkdir(serverPagesDir, { recursive: true });

      for (const layout of layoutsToCompile) {
        const absPath = resolve(root, layout.filePath);
        const outFile = layout.filePath.replace(/^src\/pages\//, '').replace(/\.tsx?$/, '.js');
        const outPath = join(serverPagesDir, outFile);
        await mkdir(join(outPath, '..'), { recursive: true });

        await esbuild({
          entryPoints: [absPath],
          bundle: true,
          format: 'esm',
          target: 'es2022',
          platform: 'node',
          outfile: outPath,
          jsx: 'automatic',
          jsxImportSource,
          plugins: [esmResolvePlugin],
          external: [],
        });

        console.log(`    ⊟ layout ${layout.dirPattern || '(root)'} → dist/server/pages/${outFile}`);
      }
    }
  }

  // 3c. Bundle browser page modules for client and hybrid pages.
  const browserPages = manifest.pages.filter(p => p.mode === 'client' || p.mode === 'hybrid');
  const clientScripts: Record<string, string> = {};
  if (browserPages.length > 0) {
    console.log(`  Bundling ${browserPages.length} browser page modules...`);
    const clientPagesDir = join(root, 'dist', 'static', '_then', 'pages');
    await mkdir(clientPagesDir, { recursive: true });

    for (const page of browserPages) {
      const absPath = resolve(root, page.filePath);
      const outFile = page.filePath.replace(/^src\/pages\//, '').replace(/\.(tsx|jsx|ts|js)$/, '.js');
      const outPath = join(clientPagesDir, outFile);
      await mkdir(join(outPath, '..'), { recursive: true });

      await esbuild({
        entryPoints: [absPath],
        bundle: true,
        format: 'esm',
        target: 'es2022',
        platform: 'browser',
        outfile: outPath,
        jsx: 'automatic',
        jsxImportSource,
        plugins: [esmResolvePlugin],
        external: [],
      });

      const scriptPath = `/_then/pages/${outFile.replace(/\\/g, '/')}`;
      clientScripts[page.filePath] = scriptPath;
      console.log(`    ◇ ${page.urlPattern} → dist/static${scriptPath}`);
    }
  }

  // 4. Build API routes + task entries
  console.log('  Building...');
  const result = await build(manifest, config, root);

  console.log(`  Server entry: ${result.serverEntry}`);
  console.log(`  Functions: ${result.functions.length} serverless bundles`);
  if (result.taskEntries.length > 0) {
    console.log(`  Tasks: ${result.taskEntries.length} task entries`);
  }

  // 5. Render build-time pages (static, client shells, and hybrid prerendered HTML)
  const staticPages = manifest.pages.filter(p => p.mode !== 'server');
  if (staticPages.length > 0) {
    console.log(`  Rendering ${staticPages.length} build-time pages...`);

    const tmpDir = join(root, 'dist', '.page-tmp');
    await mkdir(tmpDir, { recursive: true });

    const loadModule = async (filePath: string) => {
      const absPath = resolve(root, filePath);
      const result = await esbuild({
        entryPoints: [absPath],
        bundle: true,
        format: 'esm',
        target: 'es2022',
        platform: 'node',
        write: false,
        outfile: 'page.mjs',
        jsx: 'automatic',
        jsxImportSource,
        plugins: [esmResolvePlugin],
        external: [],
      });
      const bundledSource = result.outputFiles[0].text;
      return nativeImport(moduleSourceToDataUrl(bundledSource));
    };

    const outDir = join(root, 'dist');
    const rendered = await renderStaticPages(staticPages, loadModule, outDir, { clientScripts });

    for (const page of rendered) {
      console.log(`    ◆ ${page.urlPattern} → ${page.outputPath.replace(root + '/', '')}`);
    }

    // Clean up temp files
    const { rm } = await import('node:fs/promises');
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }

  // 6. Copy public assets to dist/public/ for production static serving.
  // Prefer the framework-standard root public/ directory, but support the
  // historical starter/runbook layout src/public/ when root public/ is absent.
  const publicDir = join(root, 'public');
  const legacySrcPublicDir = join(root, 'src', 'public');
  const publicSourceDir = existsSync(publicDir)
    ? publicDir
    : existsSync(legacySrcPublicDir)
      ? legacySrcPublicDir
      : null;
  if (publicSourceDir) {
    const { cp } = await import('node:fs/promises');
    const distPublicDir = join(root, 'dist', 'public');
    await cp(publicSourceDir, distPublicDir, { recursive: true });
    const label = publicSourceDir === publicDir ? 'public/' : 'src/public/';
    console.log(`  Copied ${label} → dist/public/`);
  }

  if (config.adapter) {
    console.log(`  Adapter: ${config.adapter.name}`);
  }

  // 9. Emit hot deploy templates when the project has hot routes
  const hotRoutes = manifest.api.filter(r => r.kind === 'hot');
  if (hotRoutes.length > 0) {
    const { basename } = await import('node:path');
    const rawName = basename(root);
    // sanitize to lowercase [a-z0-9-], truncate to Fly's ~30-char DNS label limit,
    // then strip any trailing dashes introduced by truncation
    const appName = rawName.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 30).replace(/-+$/, '') || 'vura-app';
    const hasWsRoutes = hotRoutes.some(r => r.hasWebsocket === true);
    const distDir = join(root, 'dist');
    await emitHotDeployTemplates(distDir, appName, hasWsRoutes);
    console.log(`  Emitted dist/Dockerfile, dist/fly.toml, dist/package.json (app: ${appName}${hasWsRoutes ? ', ws: true' : ''})`);
  }

  const elapsed = Date.now() - startTime;
  console.log(`\n  Build complete in ${elapsed}ms\n`);

  // Print route table
  console.log('  Routes:');
  for (const route of manifest.api) {
    const methods = route.methods.join(', ');
    const icon = route.kind === 'serverless' ? 'λ' : route.kind === 'hot' ? '●' : '⏳';
    console.log(`    ${icon} ${methods.padEnd(18)} ${route.urlPattern.padEnd(30)} ${route.kind}`);
  }

  for (const page of manifest.pages) {
    const icon = page.mode === 'static' ? '◆' : page.mode === 'server' ? '◈' : page.mode === 'client' ? '◇' : '⬡';
    console.log(`    ${icon} ${'PAGE'.padEnd(18)} ${page.urlPattern.padEnd(30)} ${page.mode}`);
  }

  console.log();
}
