/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WatcherHandle {
  stop(): void
}

export interface ScanResult {
  methods: Array<string>
  kind: string
  hasDefaultExport: boolean
  hasGetServerData: boolean
  pageMode: string | null
  config: any
}

/** Scan a route or page file using AST-based analysis. */
export declare function scanRoute(source: string, fileType: string): ScanResult

/** Transform JSX to What Framework h() calls. */
export declare function transformJsx(source: string, jsxImportSource?: string | undefined | null, production?: boolean | undefined | null): TransformResult

export interface TransformResult {
  code: string
  map?: string
}

/**
 * Watch a directory for file changes using native OS APIs.
 * Named Rust aliases leak into the .d.ts; pin the JS callback shape instead.
 */
export declare function watchDirectory(path: string, callback: (arg0: string, arg1: string) => any): WatcherHandle
