/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScanResult {
  methods: Array<string>
  kind: string
  hasDefaultExport: boolean
  hasGetServerData: boolean
  pageMode?: string
  config: any
}
export interface TransformResult {
  code: string
  map?: string
}
/** Scan a route or page file using AST-based analysis. */
export declare function scanRoute(source: string, fileType: string): ScanResult
/** Transform JSX to What Framework h() calls. */
export declare function transformJsx(source: string, jsxImportSource?: string | undefined | null, production?: boolean | undefined | null): TransformResult
/** Watch a directory for file changes using native OS APIs. */
export declare function watchDirectory(path: string, callback: (arg0: string, arg1: string) => any): WatcherHandle
export declare class WatcherHandle {
  stop(): void
}
